- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - cdriehuys.rds-postgres
  vars:
    aws_application_name: vanhack
    aws_tags: {}
    db_instance_name: "{{ aws_application_name }}-db"
    db_instance_size: 5
    db_instance_type: db.t2.micro

    db_instance_default_tags:
        application: "{{ aws_application_name }}"
        role: database
    db_instance_tags: "{{ db_instance_default_tags | combine(aws_tags) }}"

    db_instance_subnet: db_subnets

    # Credentials for the admin user
    db_admin_username: vanhackadmin
    db_admin_password: admin123

    db_instance_sg_rules:
      - proto: tcp
        from_port: 5432
        to_port: 5432
        cidr_ip: 0.0.0.0/0
    db_map:
        vanhack_db:
            users:
                vanhack_app: lPIldslRW
          
